version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/koron/gtc
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Build
          command: go build -v -i .
      - run:
          name: Test all
          command: go test -v ./...
